name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: App setting add secrets
      uses: microsoft/variable-substitution@v1
      with:
        files: ${{ github.workspace }}/Chuck.API/appsettings.json
      env:
        ConnectionStrings.ChuckCon: ${{ secrets.CONNECTION_STRING }}

    - name: Build
      run: dotnet build --no-restore

    - name: Test
      run: dotnet test --no-build --verbosity normal
    
    - name: Publish
      run: dotnet publish

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: Chuck
        path: ${{ github.workspace }}/Chuck.API/bin/Debug/netcoreapp5.0/publish/

  # push:

  #   runs-on: ubuntu-latest

  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: Build and Push to docker hub